// Generated by gencpp from file art_publisher/body.msg
// DO NOT EDIT!


#ifndef ART_PUBLISHER_MESSAGE_BODY_H
#define ART_PUBLISHER_MESSAGE_BODY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace art_publisher
{
template <class ContainerAllocator>
struct body_
{
  typedef body_<ContainerAllocator> Type;

  body_()
    : bodies()  {
    }
  body_(const ContainerAllocator& _alloc)
    : bodies(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::PoseStamped_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::other >  _bodies_type;
  _bodies_type bodies;





  typedef boost::shared_ptr< ::art_publisher::body_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::art_publisher::body_<ContainerAllocator> const> ConstPtr;

}; // struct body_

typedef ::art_publisher::body_<std::allocator<void> > body;

typedef boost::shared_ptr< ::art_publisher::body > bodyPtr;
typedef boost::shared_ptr< ::art_publisher::body const> bodyConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::art_publisher::body_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::art_publisher::body_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::art_publisher::body_<ContainerAllocator1> & lhs, const ::art_publisher::body_<ContainerAllocator2> & rhs)
{
  return lhs.bodies == rhs.bodies;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::art_publisher::body_<ContainerAllocator1> & lhs, const ::art_publisher::body_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace art_publisher

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::art_publisher::body_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::art_publisher::body_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::art_publisher::body_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::art_publisher::body_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::art_publisher::body_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::art_publisher::body_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::art_publisher::body_<ContainerAllocator> >
{
  static const char* value()
  {
    return "abf7cb03bbd8d63ab14e4328952a897b";
  }

  static const char* value(const ::art_publisher::body_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xabf7cb03bbd8d63aULL;
  static const uint64_t static_value2 = 0xb14e4328952a897bULL;
};

template<class ContainerAllocator>
struct DataType< ::art_publisher::body_<ContainerAllocator> >
{
  static const char* value()
  {
    return "art_publisher/body";
  }

  static const char* value(const ::art_publisher::body_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::art_publisher::body_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseStamped[] bodies\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::art_publisher::body_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::art_publisher::body_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bodies);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct body_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::art_publisher::body_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::art_publisher::body_<ContainerAllocator>& v)
  {
    s << indent << "bodies[]" << std::endl;
    for (size_t i = 0; i < v.bodies.size(); ++i)
    {
      s << indent << "  bodies[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "    ", v.bodies[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ART_PUBLISHER_MESSAGE_BODY_H
